[package]
name = "vector_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
pest = "2.1.3"
pest_derive = "2.1.0"
rustyline = "9.1.2"
thiserror = "1.0.30"
